### ISSUE TITLE
Fichiers du thème manquants (erreurs 404 dans console de debug)

### ISSUE THREAD

**Issue by LuluTchab** [epfl-si/jahiap#279]
En faisant des tests, j'ai pu voir que certains fichiers étaient référencés par le thème mais pas présents dans celui-ci.
Voici la liste que j'ai trouvée (sachant que le site était déployé sur http://localhost)

- http://localhost/wp-content/themes/epfl/assets/js/modernizr.js?ver=20151215
- http://localhost/wp-content/themes/epfl/assets/img/sprites-arrow.png
- http://localhost/wp-content/themes/epfl/assets/img/sprites.png

**Comment by LuluTchab** [comment]
Vu que ça touche tous les sites web, il suffit de check sur un des 2 que j'ai redéployé
http://test-web-wordpress.epfl.ch/v1-testwp/sccerfuries
http://test-web-wordpress.epfl.ch/v1-testwp/gr-co

**Comment by Escapevelocitycham** [comment]
Le menu fonctionne (se déroule en tout cas, pas testé les liens) mais
1) Le menu est en français alors que la page est en anglais ...
2) Sur http://test-web-wordpress.epfl.ch/v1-testwp/sccerfuries , le nom des facultés est en noir
3) Sur http://test-web-wordpress.epfl.ch/v1-testwp/gr-co , le nom des facultés est en rouge

**Comment by LuluTchab** [comment]
Hello Aline,

parmi les points soulevés par Hicham, on va déjà commencer par traiter le premier.
Dans le thème, c'est hard-codé que le fichier "header" à importer est en français. Cependant, il doit normalement coller à la langue dans laquelle la page est affichée. Je pense que suivant le plugin de gestion des langues que l'on a, il pourrait être possible de coder dans le thème d'aller chercher le contenu du cookie stockant l'ID de la langue (s'il existe) et d'inclure le bon fichier "header" en fonction.

Est-ce que ceci te parait être une solution viable ou as-tu une autre idée ?

Après, comme on ne va pas avoir que Français et Anglais comme langues, il faudra faire en sorte que si ce n'est aucune de ces 2 langues, le fichier "header" anglais sera affiché.

**Comment by alinekeller** [comment]
Alors le header est hard-codé en français parce que c'est le code que vous m'avez fourni.
Ta solution de se baser sur la langue du plugin pour définir la langue du header semble très bonne. Il faudra juste attendre d'être sûr du plugin qui sera utilisé, et là c'est du dev plus que du design donc je vous laisserai faire.

Par contre de toute façon on va changer cette bannière pour la version responsive… Je ferai les modifs de style (couleur du nom des facultés quand on aura résolu la question du header responsive).

**Comment by alinekeller** [comment]
Pour les points concernant les styles: c'est corrigé avec le passage au header responsive. Par contre le header s'affiche automatiquement en anglais 😕

**Comment by LuluTchab** [comment]
Je vais check pour voir pour l'afficher dans la bonne langue.

**Comment by LuluTchab** [comment]
Modifications faites, voir commentaire dans https://github.com/epfl-idevelop/jahiap/issues/280

**Comment by LuluTchab** [comment]
@Escapevelocitycham : Ce problème concerne tous les sites donc il suffit de regarder sur un de ceux qui a été redéployé.


Ex:
http://test-web-wordpress.epfl.ch/v1-testwp/lanes
http://test-web-wordpress.epfl.ch/v1-testwp/events

**Comment by Escapevelocitycham** [comment]
Parfait !
