### ISSUE TITLE
Supprimer les javascripts du template non-responsive

### ISSUE THREAD

**Issue by williambelle** [epfl-si/jahiap#284]
Il faudrait supprimer les javascripts du template non-responsive :

https://github.com/epfl-idevelop/container-wp-volumes/blob/e824b6839b6f38e274652261d53df1f95fa0d6a5/wp-content/themes/epfl/header.php#L22-L24

**Comment by LuluTchab** [comment]
Vu qu'on est sur un thème responsive maintenant, je considère que cette issue n'est plus d'actualité.

**Comment by williambelle** [comment]
Je ne suis pas d'accord. Il y a un mélange entre le theme non-responsive et le theme responsive.

Dans la situation actuelle, jQuery EPFL est chargé deux fois, la bannière est créée deux fois (donc deux cliques pour accepter) et les données Google Analytics collectées deux fois...

<img width="750" alt="screen" src="https://user-images.githubusercontent.com/2843501/35291873-00cb551c-006f-11e8-8763-157f3428c870.png">

Selon moi, il faut supprimer ces 3 lignes !!!

**Comment by LuluTchab** [comment]
T'as raison. De mémoire, ces 3 lignes étaient nécessaires pour le header (sinon il ne réagissait pas correctement) mais ça devait effectivement être lié encore au thème non responsive.

**Comment by LuluTchab** [comment]
@alinekeller Je me permets de te l'assigner sans passer par Hicham car c'est vraiment un truc super rapide à faire.
