### ISSUE TITLE
Lien source des images en http => "not secure" (pas de cadenas vert)

### ISSUE THREAD

**Issue by obieler** [epfl-si/jahiap#295]
**Exemple:**
**url:** https://help-wordpress.epfl.ch/pour-debuter/interface-dedition/ 

-----------------------------------------------------------------------------------
![selection_125](https://user-images.githubusercontent.com/24526380/33710103-ce1415ea-db3f-11e7-92ce-155059f88e7c.jpg)

**Comment by LuluTchab** [comment]
J'ai un blanc... est-ce qu'on met "https" dans la config WordPress lorsque l'on créé un site ?... mmm

**Comment by obieler** [comment]
En tout cas dans la table de vérité, il y a le protocole "https" dans la colonne de l'url. Après, j'ai pas vérifié plus loin.


wp_site_url:
https://wp-manager.epfl.ch
https://help-wordpress.epfl.ch

**Comment by ebreton** [comment]
Cette issue est liée au projet jahia2wp. Olivier, peux-tu la copier-coller dans une issue sur l'autre projet stp ?

**Comment by obieler** [comment]
Ok, c'est fait.
